version: "3.9"
services:
  redisgraph:
    image: "redislabs/redisgraph"
    ports:
      - "6379:6379"
  redisinsight:
    image: "redislabs/redisinsight:latest"
    volumes:
      - ".:/db"
    ports:
      - "8001:8001"
